### ISSUE TITLE
Замечания по lw0 (1)

### ISSUE THREAD

**Issue by ivklgn** [ShulepovDen/Clock#1]
приведите форматирование кода пользуясь нашим соглашением
https://github.com/lulldev/webdev/tree/master/coding-convections

так же именование переменных должно быть понятным

форматирование кода - отступы 2 пробела (html, css, js).
настройте автоматическое форматирование кода в VSCode или в другом редакторе.

подобные вещи:

```js
	if(val<10){
		val='0'+val
	}
```

должны превращаться в 

```js
if (val < 10) {
  val = '0' + val;
}
```

**Comment by ivklgn** [comment]
если возникает ситуация для однотипных элементов применить одинаковые стили - то лучше воспользоваться css классами:

```css
#hr, #min, #sec {
	background: #474646;
	padding: 10px;
	color: white;
	border-radius: 4px;
}
```
